# coding: utf-8

"""
    Music API

    **Music API with playlists**  # noqa: E501

    OpenAPI spec version: 0.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class NewPlaylist(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'song_ids': 'list[int]'
    }

    attribute_map = {
        'name': 'name',
        'song_ids': 'songIds'
    }

    def __init__(self, name=None, song_ids=None):  # noqa: E501
        """NewPlaylist - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._song_ids = None
        self.discriminator = None

        self.name = name
        if song_ids is not None:
            self.song_ids = song_ids

    @property
    def name(self):
        """Gets the name of this NewPlaylist.  # noqa: E501

        Name of the playlist  # noqa: E501

        :return: The name of this NewPlaylist.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this NewPlaylist.

        Name of the playlist  # noqa: E501

        :param name: The name of this NewPlaylist.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def song_ids(self):
        """Gets the song_ids of this NewPlaylist.  # noqa: E501

        IDs of the songs in the playlist  # noqa: E501

        :return: The song_ids of this NewPlaylist.  # noqa: E501
        :rtype: list[int]
        """
        return self._song_ids

    @song_ids.setter
    def song_ids(self, song_ids):
        """Sets the song_ids of this NewPlaylist.

        IDs of the songs in the playlist  # noqa: E501

        :param song_ids: The song_ids of this NewPlaylist.  # noqa: E501
        :type: list[int]
        """

        self._song_ids = song_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NewPlaylist):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
