/**
 * Music API
 * **Music API with playlists**
 *
 * OpenAPI spec version: 0.3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MusicApi) {
      root.MusicApi = {};
    }
    root.MusicApi.Song = factory(root.MusicApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Song model module.
   * @module model/Song
   * @version 0.3.0
   */

  /**
   * Constructs a new <code>Song</code>.
   * **Song information.**
   * @alias module:model/Song
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>Song</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Song} obj Optional instance to populate.
   * @return {module:model/Song} The populated <code>Song</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
    }
    return obj;
  }

  /**
   * ID of the song
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Title of the song
   * @member {String} title
   */
  exports.prototype['title'] = undefined;



  return exports;
}));


