# coding: utf-8

"""
    Meme Meister

    API to create memes  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.meme_info import MemeInfo  # noqa: E501
from swagger_client.rest import ApiException


class TestMemeInfo(unittest.TestCase):
    """MemeInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMemeInfo(self):
        """Test MemeInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.meme_info.MemeInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
