# coding: utf-8

"""
    Music API

    **Music API with playlists**  # noqa: E501

    OpenAPI spec version: 0.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.error_log_data import ErrorLogData  # noqa: E501
from swagger_client.rest import ApiException


class TestErrorLogData(unittest.TestCase):
    """ErrorLogData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorLogData(self):
        """Test ErrorLogData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.error_log_data.ErrorLogData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
