# coding: utf-8

"""
    Music API

    **Music API with playlists**  # noqa: E501

    OpenAPI spec version: 0.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.playlist_with_songs import PlaylistWithSongs  # noqa: E501
from swagger_client.rest import ApiException


class TestPlaylistWithSongs(unittest.TestCase):
    """PlaylistWithSongs unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlaylistWithSongs(self):
        """Test PlaylistWithSongs"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.playlist_with_songs.PlaylistWithSongs()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
