# coding: utf-8

"""
    Music API

    **Music API with playlists**  # noqa: E501

    OpenAPI spec version: 0.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_playlist_id(self):
        """Test case for delete_playlist_id

        """
        pass

    def test_get_image(self):
        """Test case for get_image

        """
        pass

    def test_get_playlist(self):
        """Test case for get_playlist

        """
        pass

    def test_get_playlist_id(self):
        """Test case for get_playlist_id

        """
        pass

    def test_post_playlist(self):
        """Test case for post_playlist

        """
        pass


if __name__ == '__main__':
    unittest.main()
