# coding: utf-8

"""
    Music API

    **Music API with playlists**  # noqa: E501

    OpenAPI spec version: 0.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.new_playlist import NewPlaylist  # noqa: E501
from swagger_client.rest import ApiException


class TestNewPlaylist(unittest.TestCase):
    """NewPlaylist unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNewPlaylist(self):
        """Test NewPlaylist"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.new_playlist.NewPlaylist()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
