/**
 * Music API
 * **Music API with playlists**
 *
 * OpenAPI spec version: 0.3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MusicApi) {
      root.MusicApi = {};
    }
    root.MusicApi.NewPlaylist = factory(root.MusicApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The NewPlaylist model module.
   * @module model/NewPlaylist
   * @version 0.3.0
   */

  /**
   * Constructs a new <code>NewPlaylist</code>.
   * **Playlist without song information.**
   * @alias module:model/NewPlaylist
   * @class
   * @param name {String} Name of the playlist
   */
  var exports = function(name) {
    var _this = this;

    _this['name'] = name;

  };

  /**
   * Constructs a <code>NewPlaylist</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NewPlaylist} obj Optional instance to populate.
   * @return {module:model/NewPlaylist} The populated <code>NewPlaylist</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('songIds')) {
        obj['songIds'] = ApiClient.convertToType(data['songIds'], ['Number']);
      }
    }
    return obj;
  }

  /**
   * Name of the playlist
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * IDs of the songs in the playlist
   * @member {Array.<Number>} songIds
   */
  exports.prototype['songIds'] = undefined;



  return exports;
}));


