/**
 * Music API
 * **Music API with playlists**
 *
 * OpenAPI spec version: 0.3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Song'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Song'));
  } else {
    // Browser globals (root is window)
    if (!root.MusicApi) {
      root.MusicApi = {};
    }
    root.MusicApi.PlaylistWithSongs = factory(root.MusicApi.ApiClient, root.MusicApi.Song);
  }
}(this, function(ApiClient, Song) {
  'use strict';




  /**
   * The PlaylistWithSongs model module.
   * @module model/PlaylistWithSongs
   * @version 0.3.0
   */

  /**
   * Constructs a new <code>PlaylistWithSongs</code>.
   * **Playlist with song information.**
   * @alias module:model/PlaylistWithSongs
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>PlaylistWithSongs</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PlaylistWithSongs} obj Optional instance to populate.
   * @return {module:model/PlaylistWithSongs} The populated <code>PlaylistWithSongs</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('songs')) {
        obj['songs'] = ApiClient.convertToType(data['songs'], [Song]);
      }
    }
    return obj;
  }

  /**
   * ID of the playlist
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Name of the playlist
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * Song(s) in the playlist
   * @member {Array.<module:model/Song>} songs
   */
  exports.prototype['songs'] = undefined;



  return exports;
}));


