# coding: utf-8

"""
    Music API

    **Music API with playlists**  # noqa: E501

    OpenAPI spec version: 0.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.error_log_data import ErrorLogData  # noqa: F401,E501


class Error(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'error_message': 'str',
        'log_data': 'ErrorLogData'
    }

    attribute_map = {
        'error_message': 'errorMessage',
        'log_data': 'logData'
    }

    def __init__(self, error_message=None, log_data=None):  # noqa: E501
        """Error - a model defined in Swagger"""  # noqa: E501

        self._error_message = None
        self._log_data = None
        self.discriminator = None

        if error_message is not None:
            self.error_message = error_message
        if log_data is not None:
            self.log_data = log_data

    @property
    def error_message(self):
        """Gets the error_message of this Error.  # noqa: E501

        Error message  # noqa: E501

        :return: The error_message of this Error.  # noqa: E501
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message):
        """Sets the error_message of this Error.

        Error message  # noqa: E501

        :param error_message: The error_message of this Error.  # noqa: E501
        :type: str
        """

        self._error_message = error_message

    @property
    def log_data(self):
        """Gets the log_data of this Error.  # noqa: E501


        :return: The log_data of this Error.  # noqa: E501
        :rtype: ErrorLogData
        """
        return self._log_data

    @log_data.setter
    def log_data(self, log_data):
        """Sets the log_data of this Error.


        :param log_data: The log_data of this Error.  # noqa: E501
        :type: ErrorLogData
        """

        self._log_data = log_data

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Error):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
