/**
 * Music API
 * **Music API with playlists**
 *
 * OpenAPI spec version: 0.3.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MusicApi);
  }
}(this, function(expect, MusicApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MusicApi.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('deletePlaylistId', function() {
      it('should call deletePlaylistId successfully', function(done) {
        //uncomment below and update the code to test deletePlaylistId
        //instance.deletePlaylistId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getImage', function() {
      it('should call getImage successfully', function(done) {
        //uncomment below and update the code to test getImage
        //instance.getImage(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPlaylist', function() {
      it('should call getPlaylist successfully', function(done) {
        //uncomment below and update the code to test getPlaylist
        //instance.getPlaylist(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPlaylistId', function() {
      it('should call getPlaylistId successfully', function(done) {
        //uncomment below and update the code to test getPlaylistId
        //instance.getPlaylistId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postPlaylist', function() {
      it('should call postPlaylist successfully', function(done) {
        //uncomment below and update the code to test postPlaylist
        //instance.postPlaylist(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
