/**
 * Meme Meister
 * API to create memes
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.MemeMeister) {
      root.MemeMeister = {};
    }
    root.MemeMeister.MemeInfo = factory(root.MemeMeister.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The MemeInfo model module.
   * @module model/MemeInfo
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>MemeInfo</code>.
   * ID and captions of meme
   * @alias module:model/MemeInfo
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>MemeInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MemeInfo} obj Optional instance to populate.
   * @return {module:model/MemeInfo} The populated <code>MemeInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('topCaption')) {
        obj['topCaption'] = ApiClient.convertToType(data['topCaption'], 'String');
      }
      if (data.hasOwnProperty('bottomCaption')) {
        obj['bottomCaption'] = ApiClient.convertToType(data['bottomCaption'], 'String');
      }
    }
    return obj;
  }

  /**
   * ID of meme
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * The text near the top of the image
   * @member {String} topCaption
   */
  exports.prototype['topCaption'] = undefined;
  /**
   * The text near the bottom of the image
   * @member {String} bottomCaption
   */
  exports.prototype['bottomCaption'] = undefined;



  return exports;
}));


