# coding: utf-8

# flake8: noqa

"""
    Music API

    **Music API with playlists**  # noqa: E501

    OpenAPI spec version: 0.3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.default_api import DefaultApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.error import Error
from swagger_client.models.error_log_data import ErrorLogData
from swagger_client.models.new_playlist import NewPlaylist
from swagger_client.models.playlist_with_songs import PlaylistWithSongs
from swagger_client.models.song import Song
